### ISSUE TITLE
RxJava 2.x variant

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxRelay#11]
Just a placeholder issue for now.

**Comment by ZakTaccardi** [comment]
I'm surprised Relays haven't been merged into the official ReactiveX specification, given how useful they are.

**Comment by dalewking** [comment]
RxJava 2.0 is now released

**Comment by dalewking** [comment]
I tried looking at starting this effort for you and it got complicated quickly. One of the issues that you have to deal with is that in RxJava 2 Action1 has become Consumer. Besides the name changes, it also allows throwing of checked exceptions. You want to implement Consumer to easily allow it to be passed to subscribe, but you don't want someone calling it to have to deal with checked exceptions.

**Comment by JakeWharton** [comment]
That's only true if you store it in a Callable-typed field/local. As long
as you reference the implementation, the checked exception can be removed
from the signature.

**Comment by dalewking** [comment]
What I was looking at doing was declaring that Relay implemented Consumer from RxJava and also a "SafeConsumer" interface that is basically Consumer without the checked exception. The same  method can implement both methods.

So that was solvable. But I got bogged down in that Relay extended Observable and RxJava 2 is not really set up for being able to extend Observable. Just discovered, looking at ObservableFromUnsafeSource that you can extend Observable, but just have to override subscribeActual

**Comment by JakeWharton** [comment]
Really? I've found Observable easier to extend with 2 because you don't
need to bother with the awkward super call and OnSubscribe interfave in the
constructor.

**Comment by dalewking** [comment]
It may be easier, but it wasn't obvious how to proceed in the limited time I looked at it.

**Comment by JakeWharton** [comment]
I'll have a look after Wednesday when I finally regain some free time.
