### ISSUE TITLE
How do I use subscribeActual method?

### ISSUE THREAD

**Issue by kuwork** [JakeWharton/RxRelay#27]
Hello,I want to build a Rxbus which base on this project . I notice that there is  a subscribeActual method in the PublishRelay class.How do I use it to build "register" and "unregister" method ? 
when I detroy the Activity ，I want to cancel the subcribe behavior.

My Rxbus is :
```java
public final class RxBus {
    private Relay<Object> bus = null;
    private static RxBus instance;

    private RxBus(){
        bus = PublishRelay.create().toSerialized();
    }

    public static RxBus getInstance() {
        if (instance == null) {
            synchronized (RxBus.class) {
                if (instance == null) {
                    instance = new RxBus();
                }
            }
        }
        return instance;
    }

    public void send(Object event) {
        bus.accept(event);
    }

    public <T> Observable<T> toObservable(Class<T> eventType) {
        return bus.ofType(eventType);
    }

    public boolean hasObservers() {
        return bus.hasObservers();
    }
}
```

**Comment by JakeWharton** [comment]
`subscribeActual` can only be implemented and called by `Observable` subclasses. You should never need to refer to it externally.

Your best bet is to not try and replicate an event bus with Rx. It's a fundamentally different architecture over which events flow. Consumers of events should directly reference their event sources for subscribing and then use the returned subscription/disposable in order to unhook.

For general Rx usage questions please use the RxJava mailing list or StackOverflow and the 'rxjava' tag.
